language: ruby
rvm:
  - 2.2.0

sudo: false
git:
  submodules: false

script: bundle exec jekyll b --trace

notifications:
  email:
    recipients:
      - eric.mill@gsa.gov
      - hillary.hartley@gsa.gov
      - gregory.boone@gsa.gov
    on_success: change
    on_failure: change

branches:
  only:
    - master
