# Base configuration
permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
pygments: true

# Title
name: HTTPS in Government
subtitle: A resource for ensuring HTTPS on .gov websites

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/https'

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: index.html
  internal: true
- text: Background
  url: pages/background
  internal: true
- text: Definitions
  url: pages/definitions
  internal: false
- text: Guidance
  url: pages/guidance
  internal: true
- text: Tools
  url: pages/tools
  internal: true
- text: Resources
  url: pages/resources
  internal: false
- text: Case Studies
  url: pages/case_studies
  internal: true


# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: HTTPS
  description: HTTPS resources
  url: https://github.com/gsa/https

# Style Variables
brand_color: "#2cb34a"
