# Override in development.
baseurl: '/https'

exclude:
- ".rbenv-version"
- README.md
- CONTRIBUTING.md
- LICENSE.md

# markdown
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
  - with_toc_data

permalink: /:title

# Site metadata
name: HTTPS in Government
subtitle: A resource for ensuring HTTPS on .gov websites.
description: "Resources, best practices, and case studies for deploying HTTPS in the federal government."


# GitHub information
repo_name: https
branch: gh-pages
gh_org: GSA
site_url: https://gsa.github.io/https

media: assets/img

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /
  internal: true
- text: Definitions
  url: /pages/definitions/
  internal: true
- text: Tools
  url: /pages/tools/
  internal: true
- text: Resources
  url: /pages/resources/
  internal: true

# Style Variables
brand_color: "#2cb34a"
