# markdown
highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions:
  - with_toc_data

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: HTTPS for .gov
description: "Resources, best practices, and case studies for deploying HTTPS in the federal government."
url: https://https.cio.gov

# GitHub information
org_name: GSA
repo_name: https
branch: master

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: HTTPS for .gov
  url: ""
  internal: true
- text: Why Everything?
  url: everything/
  internal: true
- text: FAQ
  url: faq/
  internal: true
- text: Server Name Indication
  url: sni/
  internal: true
- text: Strict Transport Security
  url: hsts/
  internal: true
- text: Mixed Content
  url: mixed-content/
  internal: true
- text: Other Technical Concepts
  url: technical-concepts/
  internal: true
- text: Resources
  url: resources/
  internal: true
